### ISSUE TITLE
Panic while unwrapping when mrt-in unit is removed from config and SIGHUP is sent

### ISSUE THREAD

**Issue by density215** [NLnetLabs/rotonda#89]
- start Rotonda with default `etc/rotonda.conf`
- edit rotonda.conf to include a mrt-in section with correct file. SIGHUP. works
- edit rotonda.conf and remove mrt-in section created in last step.

```bash
thread 'tokio-runtime-worker' panicked at src/units/rib_unit/unit.rs:635:38:
called `Result::unwrap()` on an `Err` value: Gone
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
terminating unit, processed ["../bview/latest-bview"]
SIGHUP signal received, re-reading configuration file '/Users/jasper/Projects/rotonda/rotonda-0.2/etc/rotonda.conf'
Reconfiguring target 'null'
Reconfiguring unit 'bmp-in'
Reconfiguring unit 'rib'
Starting unit 'mrt-in'
Configuration changes applied
Internal error: reconfigure command could not be sent to unit 'rib': channel closed
All components are ready.
processing ../bview/latest-bview
All components are running.
Internal error: Report links command could not be sent to gate of unit 'rib': channel closed
mrt-in: done processing ../bview/latest-bview, emitted 9842449 routes in 5s
```

**Comment by DRiKE** [comment]
Looks like this happens when `mrt-in` is still referenced on other parts of the config, e.g. the `sources` vec of the RIB unit. If you remove those references, it seems to work without issue, can you confirm that?

I guess this is a somewhat broader issue then, and we need a better configuration check before trying to apply anything.

**Comment by DRiKE** [comment]
It seems the check for such references to missing units was there but only showed an error. With
[7f8c143](https://github.com/NLnetLabs/rotonda/commit/7f8c143b53a8ad7da56573db445a62089af991bc), such invalid config will now error and terminate on startup, or in case of a SIGHUP reconfiguration, not apply the invalid config and keep running using the old config.
Perhaps there is a case of 'missing links' that is actually valid, but for now, this way the process will not get into a bogus state.

@density215 please check whether this works (it's on the towards-0.2 branch) for you.

**Comment by density215** [comment]
like a charm
