### ISSUE TITLE
Read Gzip'ed bview files directly

### ISSUE THREAD

**Issue by density215** [NLnetLabs/rotonda#99]
RIS bview files are downloaded as gzipped, would be nice if they are accepted as Rotonda mrt input as is.

**Comment by DRiKE** [comment]
First stab at this in 8f6f399.
Because we rely on OctSeq's Parser, which isn't tailored to consume streams, we need to decompress and allocate the entire file first. Compared to mmap'ing the (already) uncompressed .mrt this naturally causes higher temporary memory use.
